<a href="https://colab.research.google.com/github/choijinhyuck/CoLabTest/blob/main/PracticeForEBDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris['Class'] = load_iris().target
iris['Class'] = iris['Class'].map({0:'Setosa', 1:'Versicolour', 2:'Virginica'})
iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Class
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica
148,6.2,3.4,5.4,2.3,Virginica
149,5.9,3.0,5.1,1.8,Virginica

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.drop(columns='Class'), iris['Class'], test_size=0.2, stratify=iris['Class'])
print('X_train:',X_train.shape,'\tX_test:',X_test.shape)
print('y_train:',y_train.shape,'\ty_test:',y_test.shape)
print(y_train.value_counts())
print(y_test.value_counts())

X_train: (120, 4) 	X_test: (30, 4)
y_train: (120,) 	y_test: (30,)
Versicolour    40
Setosa         40
Virginica      40
Name: Class, dtype: int64
Virginica      10
Setosa         10
Versicolour    10
Name: Class, dtype: int64

In [10]:
from sklearn.preprocessing import RobustScaler

RuScaler = RobustScaler()
RuScaler.fit(X_train)
X_train_sc = RuScaler.transform(X_train)
X_test_sc = RuScaler.transform(X_test)

X_Original = RuScaler.inverse_transform(X_train_sc)
print(pd.DataFrame(X_Original).head(3))
print(X_train.head(3))

     0    1    2    3
0  6.0  2.9  4.5  1.5
1  5.1  3.4  1.5  0.2
2  6.4  2.7  5.3  1.9
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
78                 6.0               2.9                4.5               1.5
39                 5.1               3.4                1.5               0.2
111                6.4               2.7                5.3               1.9